CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(256) NOT NULL,
	`slug` varchar(256) NOT NULL,
	`content` text NOT NULL,
	`summary` text,
	`category` enum('prediction','analysis','course','horse','jockey','news') NOT NULL DEFAULT 'prediction',
	`raceName` varchar(128),
	`venue` varchar(64),
	`published` boolean NOT NULL DEFAULT false,
	`isAutoGenerated` boolean NOT NULL DEFAULT true,
	`seoKeywords` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `horses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`netkeibaId` varchar(32),
	`sex` varchar(4),
	`age` int,
	`heavyTrackScore` float DEFAULT 50,
	`heatScore` float DEFAULT 50,
	`smallTrackScore` float DEFAULT 50,
	`straightScore` float DEFAULT 50,
	`distanceAptitude` enum('sprint','mile','middle','long'),
	`runningStyle` enum('escape','leading','stalking','closing'),
	`totalWins` int DEFAULT 0,
	`totalRuns` int DEFAULT 0,
	`turfWinRate` float DEFAULT 0,
	`dirtWinRate` float DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `horses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jockeys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(64) NOT NULL,
	`netkeibaId` varchar(32),
	`affiliation` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`totalWins` int DEFAULT 0,
	`yearWins` int DEFAULT 0,
	`overallWinRate` float DEFAULT 0,
	`heavyTrackWinRate` float DEFAULT 0,
	`turfWinRate` float DEFAULT 0,
	`dirtWinRate` float DEFAULT 0,
	`tokyoWinRate` float DEFAULT 0,
	`nakayamaWinRate` float DEFAULT 0,
	`hanshinWinRate` float DEFAULT 0,
	`kyotoWinRate` float DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jockeys_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `race_schedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceDate` date NOT NULL,
	`venue` varchar(64) NOT NULL,
	`raceNumber` int NOT NULL,
	`raceName` varchar(128) NOT NULL,
	`grade` varchar(16),
	`distance` int,
	`surface` enum('turf','dirt') NOT NULL DEFAULT 'turf',
	`startTime` time,
	`netkeibaRaceId` varchar(32),
	`horseCount` int,
	`weather` varchar(16),
	`trackCondition` varchar(16),
	`organizer` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `race_schedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `racecourses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(64) NOT NULL,
	`code` varchar(32) NOT NULL,
	`organizer` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`location` varchar(128),
	`turfStraightDistance` float,
	`dirtStraightDistance` float,
	`turfCornerRadius` float,
	`dirtCornerRadius` float,
	`elevationDiff` float,
	`sandType` varchar(32),
	`courseNote` text,
	`isSmallTrack` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `racecourses_id` PRIMARY KEY(`id`),
	CONSTRAINT `racecourses_name_unique` UNIQUE(`name`),
	CONSTRAINT `racecourses_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
