CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(256) NOT NULL,
	`slug` varchar(256) NOT NULL,
	`content` text NOT NULL,
	`summary` text,
	`category` enum('prediction','analysis','course','horse','jockey','news') NOT NULL DEFAULT 'prediction',
	`raceName` varchar(128),
	`venue` varchar(64),
	`published` boolean NOT NULL DEFAULT false,
	`isAutoGenerated` boolean NOT NULL DEFAULT true,
	`seoKeywords` text,
	`isPinned` boolean NOT NULL DEFAULT false,
	`isBreaking` boolean NOT NULL DEFAULT false,
	`relatedPostId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceId` varchar(20) NOT NULL,
	`horseNumber` int NOT NULL,
	`frameNumber` int,
	`horseName` varchar(64) NOT NULL,
	`sex` varchar(4),
	`age` int,
	`weight` float,
	`jockeyName` varchar(64),
	`trainerName` varchar(64),
	`horseWeight` int,
	`weightDiff` int,
	`odds` float,
	`popularity` int,
	`finishPosition` int,
	`finishTime` float,
	`margin` varchar(32),
	`last3f` float,
	`passingOrder` varchar(32),
	`sire` varchar(64),
	`dam` varchar(64),
	`damSire` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `horse_master` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(64) NOT NULL,
	`nameEn` varchar(128),
	`sex` varchar(4),
	`birthDate` varchar(16),
	`coatColor` varchar(32),
	`sire` varchar(64),
	`dam` varchar(64),
	`damSire` varchar(64),
	`trainer` varchar(64),
	`owner` varchar(128),
	`breeder` varchar(128),
	`affiliation` enum('JRA','NAR') DEFAULT 'JRA',
	`record` varchar(32),
	`totalEarnings` float DEFAULT 0,
	`notableWins` text,
	`imageUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `horse_master_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jockey_master` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(64) NOT NULL,
	`affiliation` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`totalWins` int DEFAULT 0,
	`yearWins` int DEFAULT 0,
	`winRate` float DEFAULT 0,
	`placeRate` float DEFAULT 0,
	`showRate` float DEFAULT 0,
	`turfWinRate` float DEFAULT 0,
	`dirtWinRate` float DEFAULT 0,
	`heavyWinRate` float DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jockey_master_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `newsletter_subscribers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(255) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `newsletter_subscribers_id` PRIMARY KEY(`id`),
	CONSTRAINT `newsletter_subscribers_email_unique` UNIQUE(`email`)
);
--> statement-breakpoint
CREATE TABLE `payouts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceId` varchar(20) NOT NULL,
	`betType` enum('win','place','quinella','exacta','wide','trio','trifecta') NOT NULL,
	`combination` varchar(32) NOT NULL,
	`payout` int NOT NULL,
	`popularity` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `payouts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceId` varchar(20) NOT NULL,
	`predictedAt` timestamp NOT NULL DEFAULT (now()),
	`honmei` int NOT NULL,
	`taikou` int NOT NULL,
	`tanana` int NOT NULL,
	`renka` text,
	`recommendedBets` text,
	`reasoning` text,
	`isHit` boolean,
	`returnAmount` int,
	`investAmount` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `predictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `races` (
	`id` int AUTO_INCREMENT NOT NULL,
	`raceId` varchar(20) NOT NULL,
	`raceName` varchar(128) NOT NULL,
	`raceDate` varchar(10) NOT NULL,
	`postTime` varchar(5),
	`venueCode` varchar(4) NOT NULL,
	`venueName` varchar(32) NOT NULL,
	`raceNumber` int NOT NULL,
	`surface` enum('turf','dirt','steeplechase'),
	`distance` int,
	`direction` enum('right','left','straight'),
	`weather` varchar(16),
	`trackCondition` enum('good','slightly_heavy','heavy','bad'),
	`grade` varchar(32),
	`headCount` int,
	`status` enum('upcoming','entries_confirmed','results_confirmed') NOT NULL DEFAULT 'upcoming',
	`prizeMoney` float,
	`organizer` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `races_id` PRIMARY KEY(`id`),
	CONSTRAINT `races_raceId_unique` UNIQUE(`raceId`)
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`status` enum('active','trialing','canceled','past_due','expired') NOT NULL DEFAULT 'trialing',
	`trialStartedAt` timestamp,
	`trialEndsAt` timestamp,
	`currentPeriodStart` timestamp,
	`currentPeriodEnd` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
--> statement-breakpoint
CREATE TABLE `venues` (
	`id` int AUTO_INCREMENT NOT NULL,
	`venueCode` varchar(4) NOT NULL,
	`name` varchar(32) NOT NULL,
	`affiliation` enum('JRA','NAR') NOT NULL DEFAULT 'JRA',
	`location` varchar(128),
	`latitude` float,
	`longitude` float,
	`turfStraight` float,
	`dirtStraight` float,
	`elevationDiff` float,
	`isSmallTrack` boolean DEFAULT false,
	CONSTRAINT `venues_id` PRIMARY KEY(`id`),
	CONSTRAINT `venues_venueCode_unique` UNIQUE(`venueCode`)
);
