CREATE TABLE `race_predictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`race_id` varchar(20) NOT NULL,
	`race_name` varchar(256) NOT NULL,
	`venue` varchar(50) NOT NULL,
	`surface` varchar(10) NOT NULL,
	`distance` int NOT NULL,
	`race_date` varchar(10) NOT NULL,
	`start_time` varchar(10),
	`race_number` int,
	`predicted_1st` varchar(100),
	`predicted_2nd` varchar(100),
	`predicted_3rd` varchar(100),
	`jockey_1st` varchar(100),
	`jockey_2nd` varchar(100),
	`jockey_3rd` varchar(100),
	`odds_1st` varchar(20),
	`odds_2nd` varchar(20),
	`odds_3rd` varchar(20),
	`analysis_json` text,
	`betting_json` text,
	`predicted_at` timestamp NOT NULL DEFAULT (now()),
	`confidence_score` int,
	CONSTRAINT `race_predictions_id` PRIMARY KEY(`id`)
);
