CREATE TABLE `horse_race_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`horseName` varchar(64) NOT NULL,
	`raceDate` varchar(16) NOT NULL,
	`venue` varchar(64) NOT NULL,
	`raceName` varchar(128),
	`raceId` varchar(32),
	`distance` int,
	`surface` varchar(8),
	`trackCondition` varchar(16),
	`finishPosition` int,
	`horseCount` int,
	`finishTime` varchar(16),
	`last3f` varchar(8),
	`odds` varchar(16),
	`popularity` int,
	`jockey` varchar(64),
	`weight` varchar(8),
	`horseWeight` int,
	`margin` varchar(32),
	`organizer` enum('JRA','NAR') DEFAULT 'NAR',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `horse_race_history_id` PRIMARY KEY(`id`)
);
