import {
  mysqlTable,
  int,
  varchar,
  text,
  float,
  timestamp,
  mysqlEnum,
  boolean,
  decimal,
  json,
  index,
  uniqueIndex,
} from "drizzle-orm/mysql-core";

// ==========================================
// ユーザー（認証・課金用）— 既存維持
// ==========================================
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ==========================================
// サブスクリプション（課金管理）— 既存維持
// ==========================================
export const subscriptions = mysqlTable("subscriptions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  stripeCustomerId: varchar("stripeCustomerId", { length: 255 }),
  stripeSubscriptionId: varchar("stripeSubscriptionId", { length: 255 }),
  status: mysqlEnum("status", ["active", "trialing", "canceled", "past_due", "expired"]).default("trialing").notNull(),
  trialStartedAt: timestamp("trialStartedAt"),
  trialEndsAt: timestamp("trialEndsAt"),
  currentPeriodStart: timestamp("currentPeriodStart"),
  currentPeriodEnd: timestamp("currentPeriodEnd"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Subscription = typeof subscriptions.$inferSelect;
export type InsertSubscription = typeof subscriptions.$inferInsert;

// ==========================================
// ブログ記事 — 既存維持
// ==========================================
export const blogPosts = mysqlTable("blog_posts", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 256 }).notNull(),
  slug: varchar("slug", { length: 256 }).notNull().unique(),
  content: text("content").notNull(),
  summary: text("summary"),
  category: mysqlEnum("category", ["prediction", "analysis", "course", "horse", "jockey", "news"]).default("prediction").notNull(),
  raceName: varchar("raceName", { length: 128 }),
  venue: varchar("venue", { length: 64 }),
  published: boolean("published").default(false).notNull(),
  isAutoGenerated: boolean("isAutoGenerated").default(true).notNull(),
  seoKeywords: text("seoKeywords"),
  isPinned: boolean("isPinned").default(false).notNull(),
  isBreaking: boolean("isBreaking").default(false).notNull(),
  relatedPostId: int("relatedPostId"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type BlogPost = typeof blogPosts.$inferSelect;
export type InsertBlogPost = typeof blogPosts.$inferInsert;

// ==========================================
// ニュースアイテム（ピックアップニュース）
// ==========================================
export const newsItems = mysqlTable("news_items", {
  id: int("id").autoincrement().primaryKey(),
  /** タイトル */
  title: varchar("title", { length: 256 }).notNull(),
  /** サムネイル画像URL */
  thumbnailUrl: varchar("thumbnailUrl", { length: 512 }),
  /** 概要テキスト */
  summary: text("summary"),
  /** リンク先URL（外部 or 内部） */
  linkUrl: varchar("linkUrl", { length: 512 }),
  /** カテゴリ（速報/レース結果/コラム/予想） */
  category: mysqlEnum("category", ["breaking", "result", "column", "prediction"]).default("breaking").notNull(),
  /** ピックアップ表示するか */
  isPickup: boolean("isPickup").default(false),
  /** 公開日時 */
  publishedAt: timestamp("publishedAt").defaultNow().notNull(),
  /** 有効/無効 */
  isActive: boolean("isActive").default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type NewsItem = typeof newsItems.$inferSelect;
export type InsertNewsItem = typeof newsItems.$inferInsert;

// ==========================================
// メールマガジン購読者
// ==========================================
export const newsletterSubscribers = mysqlTable("newsletter_subscribers", {
  id: int("id").autoincrement().primaryKey(),
  /** メールアドレス */
  email: varchar("email", { length: 320 }).notNull().unique(),
  /** 購読者名（任意） */
  name: varchar("name", { length: 128 }),
  /** 購読ステータス */
  status: mysqlEnum("status", ["active", "unsubscribed"]).default("active").notNull(),
  /** 登録元ページ */
  source: varchar("source", { length: 256 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  unsubscribedAt: timestamp("unsubscribedAt"),
});
export type NewsletterSubscriber = typeof newsletterSubscribers.$inferSelect;
export type InsertNewsletterSubscriber = typeof newsletterSubscribers.$inferInsert;

// ==========================================
// ===== 新規: JRA公式データ対応テーブル =====
// ==========================================

// ==========================================
// 競馬場マスター
// ==========================================
export const venues = mysqlTable("venues", {
  id: int("id").autoincrement().primaryKey(),
  /** JRA場コード（01=札幌〜10=小倉） */
  venueCode: varchar("venueCode", { length: 4 }).notNull().unique(),
  /** 競馬場名 */
  name: varchar("name", { length: 32 }).notNull(),
  /** 所属（JRA/NAR） */
  affiliation: mysqlEnum("affiliation", ["JRA", "NAR"]).default("JRA").notNull(),
  /** 所在地 */
  location: varchar("location", { length: 128 }),
  /** 緯度 */
  latitude: float("latitude"),
  /** 経度 */
  longitude: float("longitude"),
  /** 芝コース直線距離（m） */
  turfStraight: float("turfStraight"),
  /** ダートコース直線距離（m） */
  dirtStraight: float("dirtStraight"),
  /** 高低差（m） */
  elevationDiff: float("elevationDiff"),
  /** 小回りコースか */
  isSmallTrack: boolean("isSmallTrack").default(false),
});
export type Venue = typeof venues.$inferSelect;
export type InsertVenue = typeof venues.$inferInsert;

// ==========================================
// レース（開催情報）
// ==========================================
export const races = mysqlTable("races", {
  id: int("id").autoincrement().primaryKey(),
  /** レース固有ID（例: 202605040811） */
  raceId: varchar("raceId", { length: 20 }).notNull().unique(),
  /** 外部データ提供元のレースID（NAR向け） */
  netkeibaRaceId: varchar("netkeibaRaceId", { length: 32 }),
  /** レース名 */
  raceName: varchar("raceName", { length: 128 }).notNull(),
  /** 開催日（YYYY-MM-DD） */
  raceDate: varchar("raceDate", { length: 10 }).notNull(),
  /** 発走時刻（HH:MM） */
  postTime: varchar("postTime", { length: 5 }),
  /** 競馬場コード */
  venueCode: varchar("venueCode", { length: 4 }).notNull(),
  /** 競馬場名（表示用） */
  venueName: varchar("venueName", { length: 32 }).notNull(),
  /** レース番号（1〜12） */
  raceNumber: int("raceNumber").notNull(),
  /** コース種別 */
  surface: mysqlEnum("surface", ["turf", "dirt", "steeplechase"]),
  /** 距離（m） */
  distance: int("distance"),
  /** 回り */
  direction: mysqlEnum("direction", ["right", "left", "straight"]),
  /** 天候 */
  weather: varchar("weather", { length: 16 }),
  /** 馬場状態 */
  trackCondition: mysqlEnum("trackCondition", ["good", "slightly_heavy", "heavy", "bad"]),
  /** グレード */
  grade: varchar("grade", { length: 32 }),
  /** 頭数 */
  headCount: int("headCount"),
  /** データステータス */
  status: mysqlEnum("status", ["upcoming", "entries_confirmed", "results_confirmed"]).default("upcoming").notNull(),
  /** 1着賞金（万円） */
  prizeMoney: float("prizeMoney"),
  /** 主催者 */
  organizer: mysqlEnum("organizer", ["JRA", "NAR"]).default("JRA").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Race = typeof races.$inferSelect;
export type InsertRace = typeof races.$inferInsert;

// ==========================================
// 出走馬（エントリー）
// ==========================================
export const entries = mysqlTable("entries", {
  id: int("id").autoincrement().primaryKey(),
  /** レースID（races.raceIdに対応） */
  raceId: varchar("raceId", { length: 20 }).notNull(),
  /** 馬番 */
  horseNumber: int("horseNumber").notNull(),
  /** 枠名（例: 1枠） */
  gateName: varchar("gateName", { length: 16 }),
  /** 枠番 */
  gateNumber: int("gateNumber"),
  /** 馬名 */
  horseName: varchar("horseName", { length: 64 }).notNull(),
  /** 馬名（英語） */
  horseNameEn: varchar("horseNameEn", { length: 128 }),
  /** 性別（牡/牝/セ） */
  sex: varchar("sex", { length: 4 }),
  /** 馬齢 */
  age: int("age"),
  /** 斤量（kg） */
  weight: float("weight"),
  /** 騎手名 */
  jockey: varchar("jockey", { length: 64 }),
  /** 調教師名 */
  trainer: varchar("trainer", { length: 64 }),
  /** 単勝オッズ */
  odds: float("odds"),
  /** 人気順 */
  popularity: int("popularity"),
  /** 着順（結果確定後） */
  finishPosition: int("finishPosition"),
  /** 走破タイム（秒） */
  finishTime: float("finishTime"),
  /** 着差 */
  margin: varchar("margin", { length: 32 }),
  /** 上がり3F（秒） */
  last3f: float("last3f"),
  /** 馬体重（kg） */
  horseWeight: int("horseWeight"),
  /** 馬体重増減 */
  horseWeightDiff: int("horseWeightDiff"),
  /** 通過順位（例: "3-3-2-1"） */
  cornerPositions: varchar("cornerPositions", { length: 32 }),
  /** 父馬 */
  sire: varchar("sire", { length: 64 }),
  /** 母馬 */
  dam: varchar("dam", { length: 64 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Entry = typeof entries.$inferSelect;
export type InsertEntry = typeof entries.$inferInsert;

// ==========================================
// 払戻金（配当）
// ==========================================
export const payouts = mysqlTable("payouts", {
  id: int("id").autoincrement().primaryKey(),
  /** レースID */
  raceId: varchar("raceId", { length: 20 }).notNull(),
  /** 券種 */
  betType: mysqlEnum("betType", ["win", "place", "quinella", "exacta", "wide", "trio", "trifecta"]).notNull(),
  /** 組み合わせ（例: "1-3-5"） */
  combination: varchar("combination", { length: 32 }).notNull(),
  /** 払戻金額（円） */
  payout: int("payout").notNull(),
  /** 人気 */
  popularity: int("popularity"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type Payout = typeof payouts.$inferSelect;
export type InsertPayout = typeof payouts.$inferInsert;

// ==========================================
// 直前オッズ履歴・騎手成績・馬騎手相性
// ==========================================
export const raceOdds = mysqlTable("race_odds", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  horseNumber: int("horse_number").notNull(),
  horseName: varchar("horse_name", { length: 64 }),
  winOdds: decimal("win_odds", { precision: 8, scale: 1 }),
  placeOddsMin: decimal("place_odds_min", { precision: 8, scale: 1 }),
  placeOddsMax: decimal("place_odds_max", { precision: 8, scale: 1 }),
  fetchedAt: timestamp("fetched_at").defaultNow().notNull(),
  minutesToStart: int("minutes_to_start"),
}, (table) => [
  index("idx_race_odds_race").on(table.raceId, table.horseNumber),
  index("idx_race_odds_time").on(table.raceId, table.fetchedAt),
]);
export type RaceOdds = typeof raceOdds.$inferSelect;

/** 正規取得した発走前の組合せオッズ履歴。確定後の払戻金とは分離して保存する。 */
export const combinationOdds = mysqlTable("combination_odds", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  betType: mysqlEnum("bet_type", ["trio", "trifecta"]).notNull(),
  /** 3連複は昇順、3連単は着順どおりに正規化した馬番組合せ（例: 1-3-5） */
  combination: varchar("combination", { length: 32 }).notNull(),
  /** 取込時点の公式オッズ（倍率） */
  odds: decimal("odds", { precision: 12, scale: 1 }).notNull(),
  fetchedAt: timestamp("fetched_at").defaultNow().notNull(),
  minutesToStart: int("minutes_to_start"),
}, (table) => [
  index("idx_combination_odds_race_time").on(table.raceId, table.fetchedAt),
  index("idx_combination_odds_lookup").on(table.raceId, table.betType, table.combination, table.fetchedAt),
]);
export type CombinationOdds = typeof combinationOdds.$inferSelect;

export const jockeyStats = mysqlTable("jockey_stats", {
  id: int("id").autoincrement().primaryKey(),
  jockeyName: varchar("jockey_name", { length: 64 }).notNull(),
  venue: varchar("venue", { length: 32 }),
  surface: varchar("surface", { length: 16 }),
  distanceRange: varchar("distance_range", { length: 16 }),
  totalRides: int("total_rides").default(0).notNull(),
  wins: int("wins").default(0).notNull(),
  seconds: int("seconds").default(0).notNull(),
  thirds: int("thirds").default(0).notNull(),
  winRate: decimal("win_rate", { precision: 5, scale: 2 }),
  placeRate: decimal("place_rate", { precision: 5, scale: 2 }),
  showRate: decimal("show_rate", { precision: 5, scale: 2 }),
  avgFinish: decimal("avg_finish", { precision: 4, scale: 1 }),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  uniqueIndex("uk_jockey_venue").on(table.jockeyName, table.venue, table.surface, table.distanceRange),
]);
export type JockeyStats = typeof jockeyStats.$inferSelect;

export const horseJockeyCompatibility = mysqlTable("horse_jockey_compatibility", {
  id: int("id").autoincrement().primaryKey(),
  horseName: varchar("horse_name", { length: 64 }).notNull(),
  jockeyName: varchar("jockey_name", { length: 64 }).notNull(),
  comboRides: int("combo_rides").default(0).notNull(),
  comboWins: int("combo_wins").default(0).notNull(),
  comboPlaces: int("combo_places").default(0).notNull(),
  avgTimeDiff: decimal("avg_time_diff", { precision: 6, scale: 2 }),
  styleMatchScore: decimal("style_match_score", { precision: 4, scale: 2 }),
  compatibilityScore: decimal("compatibility_score", { precision: 5, scale: 2 }),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  uniqueIndex("uk_horse_jockey").on(table.horseName, table.jockeyName),
]);
export type HorseJockeyCompatibility = typeof horseJockeyCompatibility.$inferSelect;

export const oddsMovementAlerts = mysqlTable("odds_movement_alerts", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  horseNumber: int("horse_number").notNull(),
  horseName: varchar("horse_name", { length: 64 }),
  oddsBefore: decimal("odds_before", { precision: 8, scale: 1 }),
  oddsAfter: decimal("odds_after", { precision: 8, scale: 1 }),
  changePct: decimal("change_pct", { precision: 5, scale: 1 }),
  alertType: mysqlEnum("alert_type", ["insider", "large_bet", "abnormal"]),
  detectedAt: timestamp("detected_at").defaultNow().notNull(),
  bonusScore: decimal("bonus_score", { precision: 4, scale: 1 }).default("0.0").notNull(),
}, (table) => [
  index("idx_alerts_race").on(table.raceId),
]);
export type OddsMovementAlert = typeof oddsMovementAlerts.$inferSelect;

/** 正規取得済みの公式データファイルをWeb取込した履歴。ファイル本文・利用キーは保存しない。 */
export const officialDataImports = mysqlTable("official_data_imports", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  source: varchar("source", { length: 48 }).notNull(),
  fileName: varchar("file_name", { length: 255 }),
  fileFormat: mysqlEnum("file_format", ["csv", "json"]).notNull(),
  rowCount: int("row_count").notNull(),
  importedByOpenId: varchar("imported_by_open_id", { length: 64 }),
  importedAt: timestamp("imported_at").defaultNow().notNull(),
}, (table) => [
  index("idx_official_import_race_time").on(table.raceId, table.importedAt),
]);
export type OfficialDataImport = typeof officialDataImports.$inferSelect;

/**
 * 契約・許諾済みのデータ提供元だけを明示的に登録するレジストリ。
 * 閲覧ページ、非公開通信、個人契約エクスポートを自動取込元として登録しない。
 */
export const authorizedDataSources = mysqlTable("authorized_data_sources", {
  id: int("id").autoincrement().primaryKey(),
  sourceKey: varchar("source_key", { length: 64 }).notNull().unique(),
  providerName: varchar("provider_name", { length: 128 }).notNull(),
  organizer: mysqlEnum("organizer", ["JRA", "NAR"]).notNull(),
  deliveryMethod: mysqlEnum("delivery_method", ["csv", "api"]).notNull(),
  /** 契約番号ではなく、契約書名・仕様書URL等の確認可能な根拠のみを保存する。 */
  authorizationReference: varchar("authorization_reference", { length: 512 }).notNull(),
  status: mysqlEnum("status", ["pending", "active", "revoked"]).default("pending").notNull(),
  /** DB保存・内部精算・集計表示など、契約で許諾された用途だけを記録する。 */
  allowedUses: json("allowed_uses").notNull(),
  approvedAt: timestamp("approved_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  index("idx_authorized_data_sources_status").on(table.status, table.organizer),
]);
export type AuthorizedDataSource = typeof authorizedDataSources.$inferSelect;
export type InsertAuthorizedDataSource = typeof authorizedDataSources.$inferInsert;

/** ファイル本文を保持せず、許諾済みデータ取込の完全性と実行結果だけを監査する。 */
export const dataImportAudits = mysqlTable("data_import_audits", {
  id: int("id").autoincrement().primaryKey(),
  sourceId: int("source_id"),
  sourceKey: varchar("source_key", { length: 64 }).notNull(),
  organizer: mysqlEnum("organizer", ["JRA", "NAR"]).notNull(),
  importKind: mysqlEnum("import_kind", ["race_list", "entries", "payouts", "odds", "combination_odds"]).notNull(),
  fileName: varchar("file_name", { length: 255 }),
  fileSha256: varchar("file_sha256", { length: 64 }),
  rowCount: int("row_count").default(0).notNull(),
  status: mysqlEnum("status", ["accepted", "rejected", "failed"]).notNull(),
  reason: varchar("reason", { length: 512 }),
  importedByOpenId: varchar("imported_by_open_id", { length: 64 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("idx_data_import_audits_source_time").on(table.sourceKey, table.createdAt),
  index("idx_data_import_audits_status").on(table.status, table.createdAt),
]);
export type DataImportAudit = typeof dataImportAudits.$inferSelect;
export type InsertDataImportAudit = typeof dataImportAudits.$inferInsert;

// 参照バッチ設計をWebアプリへ統合した、発走前の構造化予想スナップショット。
// 出走表・公式オッズ等の入力と生成結果を分けて保存し、画面閲覧時の再生成を防ぐ。
export const structuredPredictions = mysqlTable("structured_predictions", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull().unique(),
  status: mysqlEnum("status", ["succeeded", "failed"]).default("succeeded").notNull(),
  model: varchar("model", { length: 64 }).notNull(),
  sourceSnapshot: json("source_snapshot").notNull(),
  predictionJson: json("prediction_json").notNull(),
  generatedAt: timestamp("generated_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  index("idx_structured_predictions_generated").on(table.generatedAt),
]);
export type StructuredPrediction = typeof structuredPredictions.$inferSelect;

// 同一レースへの並行したLLM呼出を避けるための短期リース。
export const structuredPredictionLocks = mysqlTable("structured_prediction_locks", {
  raceId: varchar("race_id", { length: 32 }).primaryKey(),
  lockedBy: varchar("locked_by", { length: 96 }).notNull(),
  lockedUntil: timestamp("locked_until").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  index("idx_structured_prediction_locks_expiry").on(table.lockedUntil),
]);

// パドック映像解析は別フェーズ。観察値・スコアの保存枠のみ定義する。
export const paddockObservationsV2 = mysqlTable("paddock_observations_v2", {
  id: int("id").autoincrement().primaryKey(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  horseNumber: int("horse_number").notNull(),
  horseName: varchar("horse_name", { length: 64 }),
  sweatLevel: decimal("sweat_level", { precision: 3, scale: 1 }),
  gaitScore: decimal("gait_score", { precision: 3, scale: 1 }),
  heartRate: int("heart_rate"),
  muscleTension: decimal("muscle_tension", { precision: 3, scale: 1 }),
  eyeBrightness: decimal("eye_brightness", { precision: 3, scale: 1 }),
  overallCondition: decimal("overall_condition", { precision: 4, scale: 1 }),
  observedAt: timestamp("observed_at").defaultNow().notNull(),
  observerType: mysqlEnum("observer_type", ["manual", "ai_vision"]).default("manual").notNull(),
}, (table) => [
  index("idx_paddock_race").on(table.raceId, table.horseNumber),
]);
export type PaddockObservationV2 = typeof paddockObservationsV2.$inferSelect;

// ==========================================
// AI予想結果
// ==========================================
export const predictions = mysqlTable("predictions", {
  id: int("id").autoincrement().primaryKey(),
  /** レースID */
  raceId: varchar("raceId", { length: 20 }).notNull(),
  /** 予想日時 */
  predictedAt: timestamp("predictedAt").defaultNow().notNull(),
  /** 本命（◎）馬番 */
  honmei: int("honmei").notNull(),
  /** 対抗（○）馬番 */
  taikou: int("taikou").notNull(),
  /** 単穴（▲）馬番 */
  tanana: int("tanana").notNull(),
  /** 連下（△）馬番リスト（JSON配列） */
  renka: text("renka"),
  /** 推奨買い目（JSON） */
  recommendedBets: text("recommendedBets"),
  /** 予想根拠・コメント */
  reasoning: text("reasoning"),
  /** 的中結果 */
  isHit: boolean("isHit"),
  /** 回収金額（円） */
  returnAmount: int("returnAmount"),
  /** 投資金額（円） */
  investAmount: int("investAmount"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Prediction = typeof predictions.$inferSelect;
export type InsertPrediction = typeof predictions.$inferInsert;

// ==========================================
// 予想戦略別の買い目スナップショット
// ==========================================
// 通常のスコア順買い目と穴馬買い目を別々に保存し、結果確定後に個別精算する。
// 過去の旧形式予想は predictions.recommendedBets をスコア順買い目として後方互換表示する。
export const predictionTicketSets = mysqlTable("prediction_ticket_sets", {
  id: int("id").autoincrement().primaryKey(),
  predictionId: int("prediction_id").notNull(),
  raceId: varchar("race_id", { length: 32 }).notNull(),
  strategy: mysqlEnum("strategy", ["score", "longshot"]).notNull(),
  ticketData: text("ticket_data").notNull(),
  investAmount: int("invest_amount"),
  returnAmount: int("return_amount"),
  isHit: boolean("is_hit"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  uniqueIndex("uq_prediction_ticket_sets_prediction_strategy").on(table.predictionId, table.strategy),
  index("idx_prediction_ticket_sets_race").on(table.raceId, table.strategy),
]);
export type PredictionTicketSet = typeof predictionTicketSets.$inferSelect;

// ==========================================
// 非実在テスト予想（公開レース・実在出走馬から完全分離）
// ==========================================
export const syntheticPredictionRuns = mysqlTable("synthetic_prediction_runs", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull().unique(),
  label: varchar("label", { length: 128 }).notNull(),
  isSynthetic: boolean("is_synthetic").default(true).notNull(),
  /** 出走表マスターと紐付けるレースキー（未設定なら馬名の置換を行わない） */
  raceKey: varchar("race_key", { length: 64 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
});
export type SyntheticPredictionRun = typeof syntheticPredictionRuns.$inferSelect;

export const syntheticPredictionEntries = mysqlTable("synthetic_prediction_entries", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull(),
  horseNumber: int("horse_number").notNull(),
  horseName: varchar("horse_name", { length: 64 }).notNull(),
  popularity: int("popularity").notNull(),
  odds: float("odds").notNull(),
  timeDm: float("time_dm").notNull(),
  score: float("score").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  uniqueIndex("uq_synthetic_prediction_entries_run_horse").on(table.runId, table.horseNumber),
  index("idx_synthetic_prediction_entries_run").on(table.runId),
]);
export type SyntheticPredictionEntry = typeof syntheticPredictionEntries.$inferSelect;

export const syntheticPredictionOutputs = mysqlTable("synthetic_prediction_outputs", {
  id: int("id").autoincrement().primaryKey(),
  runId: varchar("run_id", { length: 64 }).notNull().unique(),
  scoreTickets: text("score_tickets").notNull(),
  longshotTickets: text("longshot_tickets").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [index("idx_synthetic_prediction_outputs_run").on(table.runId)]);
export type SyntheticPredictionOutput = typeof syntheticPredictionOutputs.$inferSelect;
export type InsertPredictionTicketSet = typeof predictionTicketSets.$inferInsert;

// ==========================================
// 出走表マスター（レースごとの馬番と本物の馬名の対応）
// ==========================================
export const raceEntryMaster = mysqlTable("race_entry_master", {
  id: int("id").autoincrement().primaryKey(),
  /** レース識別子（例: 20260822-中京-9R） */
  raceKey: varchar("race_key", { length: 64 }).notNull(),
  /** レース名（表示用） */
  raceName: varchar("race_name", { length: 128 }),
  horseNumber: int("horse_number").notNull(),
  /** 本物の馬名 */
  horseName: varchar("horse_name", { length: 64 }).notNull(),
  jockey: varchar("jockey", { length: 64 }),
  popularity: int("popularity"),
  odds: float("odds"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().onUpdateNow().notNull(),
}, (table) => [
  uniqueIndex("uq_race_entry_master_race_horse").on(table.raceKey, table.horseNumber),
  index("idx_race_entry_master_race").on(table.raceKey),
]);
export type RaceEntryMaster = typeof raceEntryMaster.$inferSelect;
export type InsertRaceEntryMaster = typeof raceEntryMaster.$inferInsert;

// ==========================================
// 馬マスター（図鑑用）
// ==========================================
export const horseMaster = mysqlTable("horse_master", {
  id: int("id").autoincrement().primaryKey(),
  /** 馬名 */
  name: varchar("name", { length: 64 }).notNull(),
  /** 英字名 */
  nameEn: varchar("nameEn", { length: 128 }),
  /** 性別 */
  sex: varchar("sex", { length: 4 }),
  /** 生年月日 */
  birthDate: varchar("birthDate", { length: 16 }),
  /** 毛色 */
  coatColor: varchar("coatColor", { length: 32 }),
  /** 父馬 */
  sire: varchar("sire", { length: 64 }),
  /** 母馬 */
  dam: varchar("dam", { length: 64 }),
  /** 母父 */
  damSire: varchar("damSire", { length: 64 }),
  /** 調教師 */
  trainer: varchar("trainer", { length: 64 }),
  /** 馬主 */
  owner: varchar("owner", { length: 128 }),
  /** 生産者 */
  breeder: varchar("breeder", { length: 128 }),
  /** 所属 */
  affiliation: mysqlEnum("affiliation", ["JRA", "NAR"]).default("JRA"),
  /** 通算成績（勝-2着-3着-着外） */
  record: varchar("record", { length: 32 }),
  /** 累計獲得賞金（万円） */
  totalEarnings: float("totalEarnings").default(0),
  /** 主な勝ち鞍 */
  notableWins: text("notableWins"),
  /** 画像URL */
  imageUrl: text("imageUrl"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type HorseMaster = typeof horseMaster.$inferSelect;
export type InsertHorseMaster = typeof horseMaster.$inferInsert;

// ==========================================
// 騎手マスター（図鑑用）
// ==========================================
export const jockeyMaster = mysqlTable("jockey_master", {
  id: int("id").autoincrement().primaryKey(),
  /** 騎手名 */
  name: varchar("name", { length: 64 }).notNull(),
  /** 所属 */
  affiliation: mysqlEnum("affiliation", ["JRA", "NAR"]).default("JRA").notNull(),
  /** 通算勝利数 */
  totalWins: int("totalWins").default(0),
  /** 今年の勝利数 */
  yearWins: int("yearWins").default(0),
  /** 全体勝率 */
  winRate: float("winRate").default(0),
  /** 連対率 */
  placeRate: float("placeRate").default(0),
  /** 複勝率 */
  showRate: float("showRate").default(0),
  /** 芝勝率 */
  turfWinRate: float("turfWinRate").default(0),
  /** ダート勝率 */
  dirtWinRate: float("dirtWinRate").default(0),
  /** 重馬場勝率 */
  heavyWinRate: float("heavyWinRate").default(0),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type JockeyMaster = typeof jockeyMaster.$inferSelect;
export type InsertJockeyMaster = typeof jockeyMaster.$inferInsert;

// ==========================================
// レーススケジュール（JRA公式カレンダーから取得）
// ==========================================
export const raceSchedules = mysqlTable("race_schedules", {
  id: int("id").autoincrement().primaryKey(),
  /** 開催日（YYYY-MM-DD） */
  raceDate: varchar("raceDate", { length: 10 }).notNull(),
  /** 競馬場名 */
  venue: varchar("venue", { length: 64 }).notNull(),
  /** レース番号（1〜12） */
  raceNumber: int("raceNumber").notNull(),
  /** レース名 */
  raceName: varchar("raceName", { length: 128 }).notNull(),
  /** グレード（G1/G2/G3/L/OP等） */
  grade: varchar("grade", { length: 16 }),
  /** 距離（m） */
  distance: int("distance"),
  /** コース種別 */
  surface: mysqlEnum("surface", ["turf", "dirt"]).default("turf").notNull(),
  /** 発走時刻（HH:MM） */
  startTime: varchar("startTime", { length: 5 }),
  /** netkeibaのレースID */
  netkeibaRaceId: varchar("netkeibaRaceId", { length: 32 }),
  /** 出走頭数 */
  horseCount: int("horseCount"),
  /** 天候 */
  weather: varchar("weather", { length: 16 }),
  /** 馬場状態 */
  trackCondition: varchar("trackCondition", { length: 16 }),
  /** 主催者 */
  organizer: mysqlEnum("organizer", ["JRA", "NAR"]).default("JRA").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type RaceSchedule = typeof raceSchedules.$inferSelect;
export type InsertRaceSchedule = typeof raceSchedules.$inferInsert;

// ===== パドック観察記録テーブル =====
export const paddockObservations = mysqlTable("paddock_observations", {
  id: int("id").primaryKey().autoincrement(),
  horseName: varchar("horseName", { length: 128 }).notNull(),
  raceId: varchar("raceId", { length: 64 }).notNull(),
  raceDate: varchar("raceDate", { length: 10 }).notNull(),
  heartRate: int("heartRate"),
  horseWeight: int("horseWeight"),
  weightDiff: int("weightDiff"),
  sweatLevel: int("sweatLevel"),
  gaitScore: int("gaitScore"),
  eyeBrightness: int("eyeBrightness"),
  excitementLevel: int("excitementLevel"),
  concentrationLevel: int("concentrationLevel"),
  obedienceLevel: int("obedienceLevel"),
  fatigueLevel: int("fatigueLevel"),
  preEjaculation: int("preEjaculation").default(0),
  coatSheen: int("coatSheen"),
  muscleTone: int("muscleTone"),
  conditionScore: int("conditionScore"),
  actualFinish: int("actualFinish"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type PaddockObservation = typeof paddockObservations.$inferSelect;
export type InsertPaddockObservation = typeof paddockObservations.$inferInsert;

// ===== パドック体調パターン学習テーブル =====
export const paddockPatterns = mysqlTable("paddock_patterns", {
  id: int("id").primaryKey().autoincrement(),
  horseName: varchar("horseName", { length: 128 }).notNull(),
  patternType: mysqlEnum("patternType", ["excellent", "good", "normal", "poor", "bad"]).notNull(),
  heartRateRange: varchar("heartRateRange", { length: 64 }),
  weightRange: varchar("weightRange", { length: 64 }),
  sweatLevelAvg: float("sweatLevelAvg"),
  gaitScoreAvg: float("gaitScoreAvg"),
  excitementAvg: float("excitementAvg"),
  concentrationAvg: float("concentrationAvg"),
  avgFinish: float("avgFinish"),
  top3Rate: float("top3Rate"),
  sampleCount: int("sampleCount").default(0),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type PaddockPattern = typeof paddockPatterns.$inferSelect;
export type InsertPaddockPattern = typeof paddockPatterns.$inferInsert;
