import { useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, Calculator, FlaskConical, RefreshCw, ShieldCheck, Target, TrendingUp } from "lucide-react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { HistoryBackButton } from "@/components/HistoryBackButton";
import {
  calculateSimulationEv,
  calculateTicketBoundary,
  calculateTicketRisk,
  createDemoSimulationEntries,
  createRecoveryRateCurve,
  type SimulationHorseInput,
} from "@shared/evSimulation";

const asNullablePositiveNumber = (value: string) => {
  if (!value.trim()) return null;
  const numberValue = Number(value);
  return Number.isFinite(numberValue) && numberValue > 0 ? numberValue : null;
};

export default function OddsSimulationPage() {
  const { user, loading } = useAuth();
  const [entries, setEntries] = useState<SimulationHorseInput[]>(() => createDemoSimulationEntries());
  const [combinationOdds, setCombinationOdds] = useState("3");
  const [ticketCount, setTicketCount] = useState("4");
  const [stakePerTicket, setStakePerTicket] = useState("100");
  const [hoveredOdds, setHoveredOdds] = useState<number | null>(null);

  const riskInput = useMemo(() => ({ combinationOdds: asNullablePositiveNumber(combinationOdds), ticketCount: Number(ticketCount), stakePerTicket: Number(stakePerTicket) }), [combinationOdds, ticketCount, stakePerTicket]);
  const results = useMemo(() => calculateSimulationEv(entries), [entries]);
  const ticketRisk = useMemo(() => calculateTicketRisk(riskInput), [riskInput]);
  const ticketBoundary = useMemo(() => calculateTicketBoundary(riskInput), [riskInput]);
  const recoveryCurve = useMemo(() => createRecoveryRateCurve(riskInput), [riskInput]);
  const activeCurvePoint = useMemo(() => {
    const targetOdds = hoveredOdds ?? ticketBoundary.currentOdds;
    if (targetOdds === null || recoveryCurve.length === 0) return null;
    return recoveryCurve.reduce((closest, point) => Math.abs(point.odds - targetOdds) < Math.abs(closest.odds - targetOdds) ? point : closest);
  }, [hoveredOdds, ticketBoundary.currentOdds, recoveryCurve]);

  const updateEntry = (id: string, field: "abilityScore" | "odds", value: string) => {
    setEntries(current => current.map(entry => entry.id === id ? { ...entry, [field]: field === "odds" ? asNullablePositiveNumber(value) : Number(value) || 0 } : entry));
  };
  const boundaryTone = ticketBoundary.status === "below" ? "border-rose-400/35 bg-rose-400/10 text-rose-100" : ticketBoundary.status === "above" ? "border-emerald-400/35 bg-emerald-400/10 text-emerald-100" : ticketBoundary.status === "at_boundary" ? "border-amber-300/35 bg-amber-300/10 text-amber-50" : "border-slate-400/20 bg-slate-400/5 text-slate-200";

  if (loading) return <div className="min-h-screen grid place-items-center bg-[#08111f] text-slate-300">読み込み中...</div>;
  if (!user || user.role !== "admin") return <div className="min-h-screen grid place-items-center bg-[#08111f] p-6 text-slate-300"><div className="text-center"><ShieldCheck className="mx-auto mb-3 text-amber-400" /><p>検証用シミュレーションは管理者専用です。</p><Link href="/" className="mt-3 inline-block text-sm text-cyan-300">ホームへ戻る</Link></div></div>;

  return <main className="min-h-screen bg-[#08111f] pb-12 text-slate-100">
    <header className="sticky top-0 z-10 border-b border-white/10 bg-[#0b1628]"><div className="mx-auto flex h-16 max-w-5xl items-center gap-3 px-4"><HistoryBackButton aria-label="前の画面へ戻る" className="rounded bg-white/5 p-2"><ArrowLeft className="w-4 h-4" /></HistoryBackButton><div className="flex-1"><h1 className="font-bold">EV・トリガミ検証シミュレーション</h1><p className="text-xs text-slate-400">商用API契約前のテスト専用機能</p></div><Link href="/admin/official-odds" className="text-xs text-cyan-300">公式オッズ取込へ</Link></div></header>
    <section className="mx-auto max-w-5xl space-y-5 px-4 pt-7">
      <div className="flex gap-3 rounded-lg border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-50"><FlaskConical className="mt-0.5 shrink-0 text-amber-300" /><div><p className="font-semibold">テストデータ専用・DB非保存</p><p className="mt-1 text-amber-100/75">ここでの値は固定テスト値または手入力値です。実在レース、公式オッズ、通常予想、的中率、精算、回収率には一切保存・反映しません。</p></div></div>
      <div className="grid gap-5 lg:grid-cols-[1.45fr_0.85fr]">
        <div className="rounded-xl border border-white/10 bg-[#0d1b2a] p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="font-semibold">能力スコアとテストオッズ</h2><p className="mt-1 text-xs text-slate-400">能力スコアをレース内で正規化し、推定勝率とEVを別々に計算します。</p></div><button onClick={() => setEntries(createDemoSimulationEntries())} className="inline-flex shrink-0 items-center gap-1 rounded border border-cyan-300/25 px-2.5 py-1.5 text-xs text-cyan-100"><RefreshCw className="w-3.5 h-3.5" />テスト値を復元</button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-white/10 text-xs text-slate-400"><tr><th className="pb-2">テスト項目</th><th className="pb-2">能力スコア</th><th className="pb-2">テスト単勝オッズ</th><th className="pb-2">推定勝率</th><th className="pb-2">EV</th></tr></thead><tbody>{results.map(result => <tr key={result.id} className="border-b border-white/5 last:border-0"><td className="py-3 font-medium">{result.label}</td><td className="py-3"><input aria-label={`${result.label}の能力スコア`} value={result.abilityScore} onChange={event => updateEntry(result.id, "abilityScore", event.target.value)} inputMode="decimal" className="w-20 rounded border border-white/10 bg-[#08111f] px-2 py-1.5" /></td><td className="py-3"><input aria-label={`${result.label}のテスト単勝オッズ`} value={result.odds ?? ""} onChange={event => updateEntry(result.id, "odds", event.target.value)} inputMode="decimal" placeholder="未入力" className="w-24 rounded border border-white/10 bg-[#08111f] px-2 py-1.5" /></td><td className="py-3 text-cyan-100">{result.estimatedWinProbability.toFixed(1)}%</td><td className={`py-3 font-semibold ${result.expectedValue === null ? "text-slate-400" : result.expectedValue < 0 ? "text-rose-300" : "text-emerald-300"}`}>{result.expectedValue === null ? "未算出" : `${result.expectedValue > 0 ? "+" : ""}${result.expectedValue.toFixed(1)}%`}</td></tr>)}</tbody></table></div><p className="mt-4 rounded bg-black/20 p-3 text-xs text-slate-400"><Calculator className="mr-1 inline w-3.5 h-3.5 text-cyan-300" />EV = （推定勝率 ÷ 100 × テスト単勝オッズ − 1）× 100。推定勝率は、入力した能力スコアの相対値から計算します。</p></div>
        <div className="rounded-xl border border-white/10 bg-[#0d1b2a] p-5"><h2 className="font-semibold">組合せオッズのトリガミ検証</h2><p className="mt-1 text-xs text-slate-400">公式組合せオッズを想定した手入力値で、最低払戻と投資額を比較します。</p><div className="mt-5 space-y-3"><label className="block text-xs text-slate-300">テスト組合せオッズ<input value={combinationOdds} onChange={event => setCombinationOdds(event.target.value)} inputMode="decimal" className="mt-1.5 w-full rounded border border-white/10 bg-[#08111f] px-3 py-2 text-sm" /></label><label className="block text-xs text-slate-300">買い目点数<input value={ticketCount} onChange={event => setTicketCount(event.target.value.replace(/\D/g, ""))} inputMode="numeric" className="mt-1.5 w-full rounded border border-white/10 bg-[#08111f] px-3 py-2 text-sm" /></label><label className="block text-xs text-slate-300">1点あたり（円）<input value={stakePerTicket} onChange={event => setStakePerTicket(event.target.value.replace(/\D/g, ""))} inputMode="numeric" className="mt-1.5 w-full rounded border border-white/10 bg-[#08111f] px-3 py-2 text-sm" /></label></div><div className={`mt-5 rounded-lg border p-4 ${ticketRisk.status === "risk" ? "border-rose-400/30 bg-rose-400/10" : ticketRisk.status === "safe" ? "border-emerald-400/30 bg-emerald-400/10" : "border-slate-400/20 bg-slate-400/5"}`}><div className="flex items-center gap-2 font-semibold">{ticketRisk.status === "risk" && <AlertTriangle className="w-4 h-4 text-rose-300" />}{ticketRisk.status === "safe" && <ShieldCheck className="w-4 h-4 text-emerald-300" />}{ticketRisk.status === "pending" ? "判定保留" : ticketRisk.status === "risk" ? "トリガミリスク" : "最低払戻は投資額以上"}</div><dl className="mt-3 space-y-2 text-xs text-slate-300"><div className="flex justify-between"><dt>総投資額</dt><dd>¥{ticketRisk.totalStake.toLocaleString()}</dd></div><div className="flex justify-between"><dt>最低想定払戻</dt><dd>{ticketRisk.minimumExpectedPayout === null ? "未算出" : `¥${ticketRisk.minimumExpectedPayout.toLocaleString()}`}</dd></div><div className="flex justify-between"><dt>損益分岐オッズ</dt><dd>{ticketRisk.breakEvenOdds === null ? "未算出" : `${ticketRisk.breakEvenOdds.toFixed(1)}倍`}</dd></div></dl></div><div className={`mt-4 rounded-lg border p-4 ${boundaryTone}`}><div className="flex items-center gap-2 text-sm font-semibold"><Target className="w-4 h-4" />トリガミ境界オッズの自動探索</div>{ticketBoundary.status === "pending" ? <p className="mt-2 text-xs opacity-80">テスト組合せオッズ・点数・金額を入力すると、損益分岐の境界値を算出します。</p> : <><p className="mt-2 text-xs opacity-85">この点数・均等購入でトリガミを避ける最小値は <strong>{ticketBoundary.boundaryOdds?.toFixed(1)}倍</strong> です。</p><p className="mt-2 text-lg font-bold">{ticketBoundary.status === "below" ? `あと ${ticketBoundary.additionalOddsNeeded?.toFixed(1)}倍 必要` : ticketBoundary.status === "above" ? `境界より +${ticketBoundary.difference?.toFixed(1)}倍` : "損益分岐ちょうど"}</p><p className="mt-1 text-xs opacity-75">現在のテストオッズ: {ticketBoundary.currentOdds?.toFixed(1)}倍</p></>}</div><p className="mt-4 text-xs text-slate-500">この結果はテスト入力だけで算出され、実際のオッズや購入判断を示すものではありません。</p></div>
      </div>
      <div className="rounded-xl border border-white/10 bg-[#0d1b2a] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 font-semibold"><TrendingUp className="h-4 w-4 text-cyan-300" />オッズ変動と期待回収率</div><p className="mt-1 text-xs text-slate-400">テスト組合せオッズを変えた場合の最低想定払戻 ÷ 総投資額 × 100 を表示します。グラフに触れると各点の値を確認できます。</p></div>{activeCurvePoint && <div className={`rounded border px-3 py-2 text-right text-xs ${activeCurvePoint.recoveryRate < 100 ? "border-rose-400/30 bg-rose-400/10 text-rose-100" : "border-emerald-400/30 bg-emerald-400/10 text-emerald-100"}`}><p>テストオッズ {activeCurvePoint.odds.toFixed(1)}倍</p><p className="mt-1 text-sm font-bold">期待回収率 {activeCurvePoint.recoveryRate.toFixed(1)}%</p></div>}</div>{recoveryCurve.length === 0 ? <div className="mt-5 grid h-70 place-items-center rounded border border-dashed border-white/10 text-sm text-slate-500">組合せオッズ・点数・金額を入力するとグラフを表示します。</div> : <><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={recoveryCurve} margin={{ top: 12, right: 18, left: -10, bottom: 0 }} onMouseMove={state => { const point = state.activePayload?.[0]?.payload as { odds?: number } | undefined; if (point?.odds !== undefined) setHoveredOdds(point.odds); }} onMouseLeave={() => setHoveredOdds(null)}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.16)" vertical={false} /><XAxis dataKey="odds" type="number" domain={["dataMin", "dataMax"]} tick={{ fill: "#94a3b8", fontSize: 10 }} tickFormatter={value => `${value}倍`} /><YAxis dataKey="recoveryRate" tick={{ fill: "#94a3b8", fontSize: 10 }} tickFormatter={value => `${value}%`} width={42} /><Tooltip contentStyle={{ background: "#0b1628", border: "1px solid rgba(148,163,184,.3)", borderRadius: 6 }} labelFormatter={value => `テストオッズ ${Number(value).toFixed(1)}倍`} formatter={(value: number, name: string) => [name === "期待回収率" ? `${value.toFixed(1)}%` : value, name]} /><ReferenceLine y={100} stroke="#fbbf24" strokeDasharray="5 5" label={{ value: "損益分岐 100%", position: "insideTopRight", fill: "#fbbf24", fontSize: 10 }} />{ticketBoundary.boundaryOdds !== null && <ReferenceLine x={ticketBoundary.boundaryOdds} stroke="#38bdf8" strokeDasharray="4 4" label={{ value: `${ticketBoundary.boundaryOdds.toFixed(1)}倍`, position: "insideTopLeft", fill: "#7dd3fc", fontSize: 10 }} />}<Line type="monotone" dataKey="recoveryRate" name="期待回収率" stroke="#22d3ee" strokeWidth={2.5} dot={{ r: 3, fill: "#22d3ee", strokeWidth: 0 }} activeDot={{ r: 5, fill: "#fbbf24", strokeWidth: 0 }} /></LineChart></ResponsiveContainer></div><div className="mt-3 flex items-center gap-3 text-[11px] text-slate-400"><span className="inline-flex items-center gap-1"><span className="h-0.5 w-5 bg-cyan-400" />期待回収率</span><span className="inline-flex items-center gap-1"><span className="h-px w-5 border-t border-dashed border-amber-300" />100%境界</span><span>入力欄またはグラフ上の値により表示が更新されます。</span></div></>}</div>
    </section>
  </main>;
}
